services:
  - type: web
    name: quicktelbundles
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SHORTCODE
      - key: PASSKEY
      - key: CONSUMER_KEY
      - key: CONSUMER_SECRET
      - key: CALLBACK_URL
        